* Overview

This is an implementation of a shell in C, I want to support basic File and Directory commands for now on linux

** TODO-List
- Implement Piping (Mostly Done)
- Environment Variables
- Handle Multi-Piping / Chain-Piping

** Resources

Here are some resources that I am using:
- Main Link :: https://valerius-petrini.vercel.app/blog/2025-06-29-fork-linux
- Similar Project :: https://github.com/Landixbtw/oshell/tree/main
- Pipes in C :: https://cs-uob.github.io/COMSM0085/exercises/part1/posix4/cpipe.html
- Pipes in C :: https://faculty.cs.niu.edu/~hutchins/csci480/linuxpipe.htm

** Rewrite

I need to rewrite this to be more like what it actually is, an
interpreter for sh/bash. This would include actual lexing/parsing and AST for
basic Piping and input redirection. I would still include the basic handling of syscalls
like chdir() inline with my code but would handle everything else with actual AST.

I also need to rewrite my piping function to be more concise as its pretty messy right now.

I need one monolithic signal handling function/method as well rather than 5 different functions.
